import type React from "react";

type Shot = {
  src: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
};

type Copy = {
  heading: string;
  wideShots: Omit<Shot, "src" | "width" | "height">[];
  generateShot: Omit<Shot, "src" | "width" | "height">;
};

const WIDE_FILES = ["recording", "minutes"];

const COPY: Record<"ja" | "en", Copy> = {
  ja: {
    heading: "スクリーンショット",
    wideShots: [
      {
        alt: "システム音声とマイクを同時に録音し、リアルタイムで文字起こしする Fennec",
        caption: "デュアルストリーム録音とリアルタイム文字起こし",
      },
      {
        alt: "エージェント CLI で生成した議事録を表示する Fennec",
        caption: "録音からそのまま AI 議事録を生成",
      },
    ],
    generateShot: {
      alt: "議事録生成のバックエンドとモデルを選ぶダイアログ",
      caption: "バックエンドとモデルを選んで生成",
    },
  },
  en: {
    heading: "Screenshots",
    wideShots: [
      {
        alt: "Fennec recording system audio and microphone together with live transcription",
        caption: "Dual-stream recording with live transcription",
      },
      {
        alt: "Fennec showing meeting minutes generated by an agent CLI",
        caption: "Meeting minutes generated straight from the recording",
      },
    ],
    generateShot: {
      alt: "Dialog for choosing the backend and model used to generate minutes",
      caption: "Pick the backend and model, then generate",
    },
  },
};

const Figure: React.FC<Shot> = ({ src, alt, caption, width, height }) => (
  <figure className="space-y-2">
    <img
      src={src}
      alt={alt}
      width={width}
      height={height}
      loading="lazy"
      decoding="async"
      className="w-full rounded-xl border border-white/15 bg-black/30 shadow-lg"
    />
    <figcaption className="text-xs text-white/70">{caption}</figcaption>
  </figure>
);

export const FennecScreenshots: React.FC<{ lang: "ja" | "en" }> = ({
  lang,
}) => {
  const copy = COPY[lang];
  const wideShots: Shot[] = copy.wideShots.map((shot, i) => ({
    ...shot,
    src: `/fennec/${WIDE_FILES[i]}.webp`,
    width: 1600,
    height: 1032,
  }));

  return (
    <section aria-labelledby="fennec-screenshots" className="space-y-6">
      <h2
        id="fennec-screenshots"
        className="text-white mb-4 border-b border-b-gray-200 pb-1 pt-2 text-2xl font-medium"
      >
        {copy.heading}
      </h2>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {wideShots.map((shot) => (
          <Figure key={shot.src} {...shot} />
        ))}
      </div>

      <div className="sm:max-w-md">
        <Figure
          {...copy.generateShot}
          src={`/fennec/${lang}/generate.webp`}
          width={1080}
          height={lang === "ja" ? 974 : 1000}
        />
      </div>
    </section>
  );
};
